# Generated by Django 4.0.5 on 2023-01-27 12:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(blank=True, null=True)),
                ('subject', models.CharField(max_length=512)),
                ('body_html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
